### ISSUE TITLE
Impossible to pass custom headers from the browser using the fetch API

### ISSUE THREAD

**Issue by atomrc** [assaf/zombie#1004]
Ok so I am trying to add custom header from my app during a `fetch` request. 
When I am running my app in test mode with Zombie, the `fetch` in my app is overridden by Zombie's `fetch`.  (https://github.com/assaf/zombie/blob/master/src/resources.js#L69)
The thing is, the `init` object comes from the browser and, for whatever reason, doesn't returns `true` when calling `init instanceof Object`.
It is a problem because it's the condition for the headers to be set to the final request that will be done against the server. (cf. https://github.com/assaf/zombie/blob/master/src/fetch.js#L25)
I am really not sure what is happening here, but it is a huge problem for me. 

Here the test code I am using : 
in `app.js`
```javascript
var params = { /*...*/ headers: { 'Content-Type': 'application/json' }};
console.log(params instanceof Object); // TRUE
fetch('/url', params)
```

in Zombie's `fetch.js`
```javascript
_fetch(input, init) {
    console.log(init.headers instanceof Object); //FALSE
}
```

I'd be happy to make a PR if you have any idea where this can come from. 
my node version is `v5.1.0`.

Thanks guys

**Comment by yaronassa** [comment]
You can add a pipeline handler that will mutate outgoing requests. 
Does something like this work for you?

```javascript
var replaceHeader = true; 
var customHeaders = [{name: "foo", value: "bar"}];

var addCustomHeaders = function addCustomHeaders(browser, request) {
    if (replaceHeader) { //Or some other condition. You can check request url, or anything else
        customHeaders.forEach(function(headerInfo){
          request.headers.set(headerInfo.name, headerInfo.value);
        });
    }
    return null; //Pass control back to the browser pipeline
};

browser.pipeline.addHandler(addCustomHeaders);
```

**Comment by atomrc** [comment]
Hmm I don't thing this will fit my needs. 
I don't really want to hardcode some custom headers in my test files. Instead I want to set the headers defined by my application's code. 
Sometime I might want an `application/json` content type and sometime a `text/plain`, and I cannot generalize this behavior in my test files. 

One fix I could think of, would be replacing the `init instanceof Object` by `init.toString === '[object Object]`.

**Comment by atomrc** [comment]
@yaronassa Ok I have reduced the problem to its simpliest form, and I still cannot understand what is happening here. 
Here is the html file I am feeding to Zombie : 
```html
<script>
  var params = { headers : { "test": "ok" }};
  console.log(params.headers instanceof Object); //TRUE
  window.fetch("/test", params); //this is the zombie's implementation of fetch
</script>
```
here is my test file
```javascript
browser.visit("/test");
```
and here are the modification I made to the `document.js` file in the zombie source code
```javascript
window.fetch = function (url, init) {
  console.log(init.headers instanceof Object); //FALSE 
  //WTF this is exactly the same object as the one I pass to the fetch method in my html file !!
  return window.resources._fetch(url, init);
}
```
I am seriously out of ideas to debug that, and my searches on Google doesn't give anything for the moment. 
So if you have any idea it'd be awesome.

Thanks

**Comment by atomrc** [comment]
I don't know if it could help but here is another test I ran inside zombie's code : 

```javascript
window.fetch = function (url, init) {
  var t = {};
  console.log(t instanceof Object);  //TRUE
  console.log(Object.getPrototypeOf(t)); // {}
  console.log(init instanceof Object); //FALSE
  console.log(Object.getPrototypeOf(init));  //Object {}
  return window.resources._fetch(url, init);
}
```
the log is
```
true
{}
false
Object {}
```
I have no idea why the two object seems to have a different prototype. `t` is a `{}` while `init` is a `Object {}`
This is really curious ...

**Comment by atomrc** [comment]
I made progress here :)
It actually comes from the `VM.runInContext` call in `document.js`

Here is a very simple js file you can run into node and see the same effect as what I am experimenting. 
I am not sure what we can do about that, but it's pretty annoying!

```javascript
var vm = require("vm");

var t = {
    test: function test(obj) {
       var t = {};
       console.log(t);
       console.log(t instanceof Object);
       console.log(obj);
       console.log(obj instanceof Object);
   }
};

var sand = vm.createContext(t);

vm.runInContext("test({})", t);
```

**Comment by atomrc** [comment]
Any idea when next release including this fix is going to be out ?
