### ISSUE TITLE
Error: Cannot find module 'zombie'

### ISSUE THREAD

**Issue by chaowei** [assaf/zombie#1010]
I am a newbie to zombie. My problem is the following.

I created a file named test.js with the following 2 lines as content:
console.log("Start!");
const Browser = require('zombie');

then I run "node test.js" and there is an error:
Error: Cannot find module 'zombie'

I can not understand why it happens. I installed zombie under MAC with the following command:
sudo npm install -g zombie --save-dev

I tried both node.js v4.2.3 and v5.2.0 and all happens so.

Thanks for answer my question!

**Comment by sintanial** [comment]
Have you tried install zombie locally (with package.json) ?

**Comment by chaowei** [comment]
I tried install zombie locally and it works. But it cannot work if install globally.

Another question by the way: 
Does "Browser.localhost(host, port)" mean to specify a local proxy for host?

**Comment by sintanial** [comment]
I dont know whats do Browser.locslhost. But use proxy like this browser.proxy="user:pass@host:port"

**Comment by chaowei** [comment]
could not understand what's the use and purpose of "Browser.localhost(host, port)".
It seems useless???
