### ISSUE TITLE
I could not see any 4.2.1 on the release branch,  not sure why has happened. 

### ISSUE THREAD

**Issue by BinChang** [assaf/zombie#1012]
npm landing page suggests that latest version is 4.2.1

**Comment by assaf** [comment]
https://github.com/assaf/zombie/commit/d07867ddabce6aaec8731a35550b533c4e79f53b

**Comment by aslakhellesoy** [comment]
Looks like the latest release [tagged in git](https://github.com/assaf/zombie/tags) is 4.0.13. Will future releases be tagged?

**Comment by mdlavin** [comment]
I'll try to tag future released in git.
