### ISSUE TITLE
How could I use jQuery in Zombie?

### ISSUE THREAD

**Issue by chaowei** [assaf/zombie#1018]
Is there any possibility to use jQuery and other js libraries in Zombie?
like in Phantomjs there is a includeJs() method:

  page.includeJs("http://ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js", function() {
    page.evaluate(function() {
      $("button").click();
    });
    phantom.exit()
  });

**Comment by sintanial** [comment]
Try this way:
```javascript
browser.evaluate(`
var jqScript = document.createElement("script");
jqScript.src = "http://ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js";
document.body.appendChild(jqScript);
`);
browser.wait().then(()=>{
    browser.evaluate(`$("button").click();`);
})
```
