### ISSUE TITLE
Is it possible to query for the graphical output?

### ISSUE THREAD

**Issue by trusktr** [assaf/zombie#1020]
Can we somehow access a buffer where the headless Zombie's thoughts would be rendered to, so we can for example pipe it to a framebuffer?

**Comment by assaf** [comment]
Zombie doesn't render anything, there's no graphical output.

**Comment by trusktr** [comment]
Well, I know there isn't any (at least by default), but it'd be useful (for what I want to do) if there was a way to make it output somewhere manually.

**Comment by assaf** [comment]
There is no rendering whatsoever.

**Comment by trusktr** [comment]
For sure, thanks!
