### ISSUE TITLE
increase text contrast in docs

### ISSUE THREAD

**Issue by avdd** [assaf/zombie#1025]
please use darker text in the documentation.

http://contrastrebellion.com/

**Comment by assaf** [comment]
The documentation doesn't have any coloring, it's just a Markdown file. Any color scheme/fonts/grid/etc are applied by the viewer, so you can choose a different Markdown viewer, or read the raw text.

**Comment by avdd** [comment]
http://zombie.js.org/

Looks like HTML and CSS to me.

**Comment by assaf** [comment]
That page is hosted by Github and uses their default theme, but the content is README.md which is Markdown with no styling, so you can use any viewer that suites your needs.

**Comment by ForbesLindesay** [comment]
Closing this as we know documentation is lacking, see #799 but the markdown has plenty of contrast if you read it on GitHub.
