### ISSUE TITLE
unable to catch a redirect event...

### ISSUE THREAD

**Issue by lynzt** [assaf/zombie#1056]
I am trying to catch a 3xx redirect using `browser.on('redirect')`. I can see the event "emit" but cannot figure out how to catch it.

A simple example using `node v4.4.3`, `mocha` and `google.com` (note - trying to hit `google.com` 301 redirects to `www.google.com`). 
```
describe('Request google.com', function() {
  const browser = new Browser();
  before(function() {
    return browser.visit('http://google.com');
    // return browser.visit('http://www.google.com');
  });

  before(function() {
    return browser.on('redirect', function(request, response) {
      console.log("this was redirected...");
    });
  });

  it('Should be successful and redirected', function() {
    browser.assert.success();
    browser.assert.redirected('this should 301 redirect');
  });
});
```

The `assert.redirected` works as expected. I'm wondering if I'm just trying to catch the event wrong. I've tried moving the `on('redirect')` to different places but it never comes back as being fired.

**Comment by assaf** [comment]
First listen to the event, then run the code that triggers it.

**Comment by lynzt** [comment]
Ah, I knew it must be something silly I was doing. Thanks! 👍
