### ISSUE TITLE
Support node v6

### ISSUE THREAD

**Issue by mdlavin** [assaf/zombie#1075]
Supporting node v6 requires a couple different PRs to be merged and this issue tracks the list of what needs to be done. So far, the PRs that are needed are:

PR #1033 
PR #1074 
PR #1073 
PR #1072

**Comment by mdlavin** [comment]
@assaf My fork of zombie with v6 support has been used for a while now and I haven't heard of any issues with it. Would you mind merging the fixes into master and releasing a new version so that others can get v6 support?

If you don't mind sharing access to the project, I'm happy to do my part in helping maintain zombie. I could merge and release versions as needed.

**Comment by assaf** [comment]
Thanks. Going to add you as collaborator on Github and npm.

**Comment by mdlavin** [comment]
Thank you so much! I'll merge the branch and clean up some of the PRs.

**Comment by mdlavin** [comment]
I've merged the changes, and published a the version v4.3.0 with node v6 support.
