### ISSUE TITLE
Is this repo dead? no merges since Jan, and things are breaking as things are getting old?

### ISSUE THREAD

**Issue by si-mikey** [assaf/zombie#1077]
what happened to the maintainer??

**Comment by mdlavin** [comment]
I've recently been given the ability to merge and release new version (and my first release added node v6 support a couple of min ago).

I'll try to help maintain the project as much as I can. Like always, PRs will be preferred over bug reports =).

**Comment by slauyama** [comment]
@mdlavin If there is only node v6 support can we put that on the documentation? Ive been trying to use node v8 with zombie and it seems to be failing

**Comment by mdlavin** [comment]
I haven't had time to do any development in this project for a while. I'd
be ok with stepping down as a maintainer and putting somebody in my place
if anybody is interested. I think I've seen assaf do some merging in the
not too distant past.

**Comment by slauyama** [comment]
I think I'll just make a change to the README saying that this is only maintained up to node 6 that way people can see it.
