### ISSUE TITLE
problem with filling out a input

### ISSUE THREAD

**Issue by ludwigmeier** [assaf/zombie#1081]
I try to fill out the input with the name "dynvalue[fcpo_elv_iban]" with an IBAN to test the whole process of buying an article inside my shop. I got no error from zombie.js.

I tried: browser.fill('dynvalue[fcpo_elv_iban]','**_MYIBAN**_*');

`<tr>
          <td></td>
          <td valign="top"><label>IBAN:</label></td>
          <td>
            <input class="mx-input mx-input-middle" type="text" size="20" maxlength="64" name="dynvalue
[fcpo_elv_iban]"
             value=""><br><br>
            <span class="fcpoerrorbox">
              <div id="fcpo_elv_iban_invalid" class="fcpo_check_error">
                <div class="fcPayOneErrorContent">Bitte geben Sie eine korrekte IBAN ein.</div>
              </div>
            </span>
          </td>
        </tr>`
can someone help? Thanks,

**Comment by daniellutz** [comment]
Try with this one:

```javascript
 browser.assert.input('input[name="dynvalue[fcpo_elv_iban]"]', 'MYIBAN*');
```

:)

**Comment by mdlavin** [comment]
@ludwigmeier can you say whether daniellutz's comment helped you?

**Comment by ludwigmeier** [comment]
I Finally Used selenium Webdriver and this function 
driver.findElement(By.name("dynvalue[fcpo_elv_iban]")).sendKeys("MYIBAN")
