### ISSUE TITLE
Release new version with a more recent `jsdom`

### ISSUE THREAD

**Issue by dresende** [assaf/zombie#1084]
Now that you're using a more recent `jsdom` version, release a new version.

https://nodesecurity.io/advisories/130

**Comment by dresende** [comment]
`jsdom@5.3.0` uses `touch-cookie<1.0.0` ([package.json](https://github.com/tmpvar/jsdom/blob/db257df675fd2264adbe8a7f3783a72bccce25ef/package.json))

**Comment by mdlavin** [comment]
I published a new version of zombie, 5.0.0, with the jsdom 7.x adoption.
