### ISSUE TITLE
How to access jsdom instance?

### ISSUE THREAD

**Issue by deyceg** [assaf/zombie#1098]
Hey,

Is there a way to access the underlying jsdom instance? I'm trying to bridge cucumber js/zombie/enzyme.

I'm not entirely sure if zombie/enzyme would use the same instance of jsdom through normal require mechanics as theres some very specific setup for enzyme/jsdom:

```
/* setup.js */

var jsdom = require('jsdom').jsdom;

global.document = jsdom('');
global.window = document.defaultView;
Object.keys(document.defaultView).forEach((property) => {
  if (typeof global[property] === 'undefined') {
    global[property] = document.defaultView[property];
  }
});

global.navigator = {
  userAgent: 'node.js'
};
```

Whilst not related to zombie, im trying to mount a react/redux app into jsdom to perform some BDD style tests using .feature files (gherkin syntax).

Not got alot of experience with Zombie so I may be able to cut out enzyme completely!

**Comment by mdlavin** [comment]
It would be a bit of a hack, but you could try `require('zombie/dom')` and see if that gives you the access you want.

**Comment by deyceg** [comment]
@mdlavin I went with this instead and it appears to be working:

```
this.browser.visit('http://localhost', function(){
      var jsdom = require('jsdom').jsdom;
      var exposedProperties = ['window', 'navigator', 'document'];

      global.document = b.document;
      global.window = b.document.defaultView
      Object.keys(document.defaultView).forEach((property) => {
        if (typeof global[property] === 'undefined') {
          exposedProperties.push(property);
          global[property] = document.defaultView[property];
        }
      });

     // Able to mount react app now
})
```
