### ISSUE TITLE
[BUG] window.matchMedia is not a function

### ISSUE THREAD

**Issue by HiveSolution** [assaf/zombie#1120]
When Javascript tries to access `window.matchMedia` the error `not a function` is thrown.

This could be fixed by using a small polyfill that needs to be added to the pages head, or by adding the polyfill directly to zombie.

This could be done by adding it to the `lib/dom/scripts.js`.

Both work just fine.

Is polyfilling missing libs in scope of zombie or should the WebApp polyfill everything? If it's in the scope and you want that change I can create a PR fixing this issue.

**Comment by mike-feldmeier** [comment]
I am coming across this scenario as well.  I would love to see the polyfill included in zombie.  In our situation, we don't always have complete control over the website being tested.

**Comment by cambaughn** [comment]
I'm running into this as well, and it seems like it would be a more common problem, particularly if you're loading up a site you don't have full control over.

**Comment by noreplydev** [comment]
Here running into this also.
