### ISSUE TITLE
Why zombie does not work with localstorage?

### ISSUE THREAD

**Issue by DmitryPacificAtion** [assaf/zombie#1149]
I see that Zombie has functions to work with local storage, but i can not set, or get, or remove items, like in plain browser (Chrome or Firefox). How does it works?
When i wrote browser.localStorage.setItem('token', '123');  i see **TypeError: browser.localStorage.setItem is not a function**

**Comment by DmitryPacificAtion** [comment]
Thanks!

**Comment by xurei** [comment]
Just went through this problem as well. Any reason why it's not in the docs ?
