### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by lirantal** [assaf/zombie#1169]
Hello,

As a member of the [Node.js Security WG](https://hackerone.com/nodejs-ecosystem)
I would like to draw your attention to a security report that has been made regarding this issue.

I have made attempts to contact the person identified as a maintainer of this package but did not get any answer. What is the best way to reach someone with commit rights over this repo and hopefully npm publishing rights as well, in order to invite them to privately discuss the issue on the HackerOne platform and provide a resolution? 

Thanks,
Liran.

References:
* [Node.js Security WG ecosystem vulnerability processes](https://github.com/nodejs/security-wg/blob/master/processes/third_party_vuln_process.md)

**Comment by djanowski** [comment]
I'm a collaborator, contact me at the email address publicly listed on my
profile, thanks

**Comment by vladgurgov** [comment]
+1

**Comment by lirantal** [comment]
@djanowski I invited you to the hackerone platform, you should get an invite in your inbox.
Please join and review the report to take action on.

Thanks!

**Comment by lirantal** [comment]
@djanowski can you please check again your inbox or spam folder for the invite?
appreciate it!

**Comment by lirantal** [comment]
All, @assaf, I'm chiming in on this again as I have disclosed the report (https://hackerone.com/reports/389583) but before it makes it to a CVE that will affect this and future versions of Zombie, would you like to further discuss?

My action item would be that if Zombie can default to not evaluating javascript code when crawling a website then this will be a good security measure. Not sure however what and if this will break existing clients. Can you share your input?
