### ISSUE TITLE
browser.fill().fill() not a function

### ISSUE THREAD

**Issue by mrsilver512** [assaf/zombie#1176]
Before upgrading to Zombie V6.1.3, the browser.fill().fill() will work. However upon upgrading to Zombie V6.1.3, the test fails and returns as not a function.

Node Version: v10.11.0
macOS Version: Mojave (10.14)

**Comment by jatinseth2007** [comment]
I am facing the same erro

**Comment by TheFive** [comment]
i have split my calls from
browser.fill().click()
to 
browser.fill()
browser.click()

fill now returns a promise (as i have understood the update docu) and not a browser.

**Comment by MiloATH** [comment]
This is intended behavior (#1054). Consider something along the lines of the following instead:
```js
browser.fill('email', 'zombie@underworld.dead')
  .then(() => browser.fill('password', 'eat-the-living'))
  .then(() => browser.pressButton('Sign Me Up!', done));
```
This issue can be closed.

**Comment by assaf** [comment]
👍

**Comment by avimar** [comment]
Can you please update the quick-start on the "The Bite" please? I google it and found this right away, so it's wasn't too bad. After that change, it seemed to work fine!
http://zombie.js.org/

It lists:

```
    before(function(done) {
      browser
        .fill('email',    'zombie@underworld.dead')
        .fill('password', 'eat-the-living')
        .pressButton('Sign Me Up!', done);
    });
```

**Comment by Roxar7** [comment]
It looks like the documentation in http://zombie.js.org/ is outdated and still lists:

````    
before(function(done) {
      browser
        .fill('email',    'zombie@underworld.dead')
        .fill('password', 'eat-the-living')
        .pressButton('Sign Me Up!', done);
    });
````

Can somebody help to update it ?
