### ISSUE TITLE
browser.fire 'click' not working with eventHandlers added via Backbone.Events

### ISSUE THREAD

**Issue by cjroebuck** [assaf/zombie#181]
In my test when I do 

```
target = browser.querySelector('#target-selector')
browser.fire 'click', target, @callback', 
```

the event is dispatched and the callback is called, but the click event handler on that element does not fire.

However, if I do

```
browser.evaluate "$('#target-selector').click()" 
```

then the click event handler runs. Any reason why browser.fire would not act the same.

using zombie 0.10.1

PS this only happens for event handlers that are attached by Backbone, here is a gist showing this problem:

https://gist.github.com/1256944

**Comment by beldougie** [comment]
Just wondering why this is closed? It's not fixed and is still a problem in the current code base. If I execute clickLink on a valid link, my backbone event handler should augment the href and it does not get called at all. This works perfectly in a 'real' browser. Are you actually going to fix any of these bugs or has support ceased on this project? All I can see here is curt, one-line responses which show little to no respect for any of your users and which don't actually address any of the issues being raised. 

As a lot of us are using this in tests on real projects, it would be good to know if we should just go and use an alternative solution?

**Comment by assaf** [comment]
This issue references an event handling bug in the DOM, which affects jQuery/Backbone/others. A while back, brianmcd works on and contributed a fix, I added a test case to make sure this doesn't regress. Zombie has been shipping with that fix and accompanying test for 2 years now!

If you determined there's another bug lurking in there, you're more than welcome to open a new issue. If you submit a pull request with a test case and a fix, then I will review it and merge it into a future release, as I do with all bug fixes.
