### ISSUE TITLE
jquery event handler/listener completely ignored

### ISSUE THREAD

**Issue by ezmilhouse** [assaf/zombie#217]
I like the idea behind zombie, but it totally ignores jquery's event handling.

Example

<a href="/noscript/side" class="some-class">
    Test Javascript
</a>

$(document).on('click', '.some-class', null, function(evt){
    evt.preventDefault();
    window.location.href = '/other/side';
});

Use zombie's fire or clickLink - both will end up landing on /noscript/side - don't know why, maybe it's the preventDefault() that is the problem, but as long as event delegation is not supported, zombie seems to be pretty much useless ... did I miss something?

**Comment by beldougie** [comment]
It ignores backbone event handling too - quickly becoming an unusable project for anything other than very simple page scraping. Trying to use as a smoke-test solution is proving problematic. I know @assaf said this was fixed - but it's almost 3 years later and it's clearly not... :(

**Comment by assaf** [comment]
Here's the test case for jQuery live events: https://github.com/assaf/zombie/blob/master/test/jquery_compat_test.js#L149
