### ISSUE TITLE
Zombie: require is not defined ReferenceError: require is not defined

### ISSUE THREAD

**Issue by joques** [assaf/zombie#258]
Hi,
I am using zombie.js to test the UI part of a node.js app (written in coffee-script). Basically, what I do is take a form, fill in a few fields, click a button as described here https://gist.github.com/b341318b26dbc5f4af11

The tests pass, but there is a message, which I failed to understand. Once it tries to access app.'s it throws an error, indicated in the title. **_Zombie: require is not defined ReferenceError: require is not defined**_

The complete output of the test is pasted here https://gist.github.com/c9e22ed9c4e1be20f2c4

Can someone please explain to me what that means?
José

**Comment by cefn** [comment]
For reference I get the same error when loading http://www.bbc.co.uk/news although no such error is shown in the Chromium Javascript console when visiting the same page.

    zombie.visit("http://www.bbc.co.uk/news");

This is running with the latest version of JSDOM and Zombie compatible with Node... 

```
 "name": "jsdom",
  "version": "3.1.2",
```

```
  "name": "zombie",
  "version": "4.0.8",
```
