### ISSUE TITLE
fire KeyPress events on fields

### ISSUE THREAD

**Issue by mgan59** [assaf/zombie#275]
I'm looking to test a series of autocompleters, specifically I want to be able to fire keyPress events on a field and monitor that an html-control is being populated with a list of html results.

I looked into the zombiejs browse and eventloop code.  I'm new to this code, but I see the lines 230 in [browser.coffee](https://github.com/assaf/zombie/blob/master/lib/zombie/browser.coffee#L230)

```
type = if name in MOUSE_EVENT_NAMES then "MouseEvents" else "HTMLEvents"
event = @window.document.createEvent(type)
event.initEvent name, true, true 
```

So assuming the [DOM Level 3 events for KeyboardEvent](https://developer.mozilla.org/en/DOM/document.createEvent) needed added?

**Comment by skyl** [comment]
I need `event.initMouseEvent`. I wonder how easy this would be to patch in against 2.5.1.
