### ISSUE TITLE
Support for navigator.geolocation

### ISSUE THREAD

**Issue by tleach** [assaf/zombie#387]
I'm attempting to use zombie to test a page I've written which uses the new HTML5 Geolocation API (`navigator.geolocation`) to populate a couple of lat/lon hidden fields which get submitted as part of a form. 

What I'd really like to be able to do in my test is to give zombie some mock location details which it would then return to my page's JS code when it calls `navigator.geolocation` so that I can verify those details are being handled correctly. 

I've scoured the API docs but can't find any indication of whether this is supported and how it could be done. 

Is this supported and if not, is there a clever workaround anyone can suggest?

**Comment by rbaprado** [comment]
Is there a way to edit the navigator object prior to loading pages? This could be way to mock the geolocation functionality...

**Comment by assaf** [comment]
There's an `open` event you can hook into: https://github.com/assaf/zombie#opened-window
