### ISSUE TITLE
DOMWindow memory leak

### ISSUE THREAD

**Issue by ghost** [assaf/zombie#397]
I am in the process of writing a test framework using zombie for hundreds of domains. The intent is to have it run each test every 10 minutes, using a fresh Browser object each time to not have any data shared between tests (I have no control over the contents of pages being visited in tests). This means I create roughly a thousand new Browser objects each minute. The problem with this is that currently Zombie is leaking memory like a madman.

Consider this chunk:

``` javascript
var Browser = require('zombie').Browser;
setInterval(function() {
    var browser = new Browser();
}, 10);
```

After roughly half a minute of execution, I have roughly 10,000 DOMWindow objects in memory. According to [this JSDOM issue](https://github.com/tmpvar/jsdom/issues/226), this happens if you don't execute JSDOM's window.close() method. Looking at the windows.coffee file, Zombie currently does not. It actually even overwrites that function with its own, and the new one does not invoke dispose() on the context.

I tried adding that call to the Windows::close method, but it seems close() is invoked very early. In order to get more control over it, I made it a separate Windows::destroy() function using the code below. This works somewhat, but throws exceptions both left and right if there are lingering requests.

``` coffeescript
Windows::destroy = (window) ->
    return if window.__disposed
    @close window
    window.__original_close()
    window.__disposed = true

__original_createWindow = JSDOM.createWindow
JSDOM.createWindow = (dom, options) ->
    window = __original_createWindow.call JSDOM, dom, options
    return window unless window?
    window.__original_close = window.close
    return window
```

So I also added this to the top of the callback in History::_resource:

``` coffeescript
return if @_window.__disposed
```

Now I get no more exceptions, but instead Contextify randomly segfaults after 30-50 browser objects, due to attempting to fetch a property that it shouldn't. Thinking it was due to some timers still running, I also added the below call and used that instead of Windows::destroy().

``` coffeescript
Browser::destroy = () ->
    @_eventloop.reset()
    @windows.destroy(@window) while (@windows.count > 0)
```

The segfault remains though. This really needs to get fixed and I wouldn't mind doing it myself and send a pull request back, but I am at a loss as to how to proceed. Any pointers or fixes would be much appreciated.

**Comment by ahmed-shehata** [comment]
browserInstance.close()
browserInstance.destroy()

do not work, still leaking..
