### ISSUE TITLE
FATAL ERROR: CALL_AND_RETRY_2 Allocation failed - process out of memory

### ISSUE THREAD

**Issue by maccman** [assaf/zombie#489]
We're getting the following error when using Zombie:

FATAL ERROR: CALL_AND_RETRY_2 Allocation
failed - process out of memory

Unfortunately there's no additional backtrace. I'm just opening this ticket to see if anyone else has experienced similar problems.

**Comment by Vikasg7** [comment]
hello assaf,

How do you suggest that how we should clear the memory or history ??
I am running into same problem. I have done a scraper where its throwing the same error after doing 200 websites.

Shall I create new zombie object for each request or there is a better way of doing this ??

Regards,
