### ISSUE TITLE
Unknown pseudo-class selector ":contains"

### ISSUE THREAD

**Issue by bigattichouse** [assaf/zombie#587]
Erg.

Prior to recent update (html5?) - I could do 
browser.querySelector("#some-div-id table thead tr th:contains('Percent') span:contains('%')")

now I get:
Error: Unknown pseudo-class selector ":contains('Percent') *:contains('%')"

This happens no matter what the th selector is, as well as the spans contains.

**Comment by darkbasic** [comment]
The lack of sizzle selectors is really annoying, any chance to reintroduce them?
Unfortunately I cannot rely on browser.eval("jQuery('#myobj:contains(\"Sometext\")')") because the page doesn't have JQuery :(

**Comment by darkbasic** [comment]
nwmatcher (used by JSDOM) states has legacy support for contains through optional external add-on:
https://github.com/dperini/nwmatcher/wiki/CSS-supported-selectors

Any chance to optionally enable such support in Zombie.js when instantiating the object?
