### ISSUE TITLE
How do you connect to an https site with a self signed certificate?

### ISSUE THREAD

**Issue by trusktr** [assaf/zombie#605]
I have a https test site with a self signed certificate (the ones that make your browser show a warning message). Zombie doesn't seem to get any content from it. console.log(browser.html()) shows nothing. Is there something else I have to do to make this work?

**Comment by medikoo** [comment]
I just approached this today (using zombie v4.1.0) and only @cmbirge suggestion fixed it for me

**Comment by alexserver** [comment]
@medikoo :+1: 
@assaf how can we have this set as a constructor option in zombie.js ?

**Comment by yuyudhan** [comment]
@cmbirge 

> Try setting process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0" in your application.

This sets SSL off for all http requests in the process. Shutting off all together would be drastic in production use.

Do you know how to set it off for one particular request. Anyone??

**Comment by khullah** [comment]
@yuyudhan not elegant, but can't you toggle that whenever needed?
