### ISSUE TITLE
Injecting javascript into zombie

### ISSUE THREAD

**Issue by jsloyer** [assaf/zombie#629]
Is there a way to inject a javascript include in zombie?  Basically I would like to include a jquery plugin just for testing my site.

I saw a previous issue that mentioned browser.evaluate()

**Comment by JulianKingman** [comment]
How is this done? I couldn't find relevant documentation on either option. For example:
````javascript
browser.evaluate('https://ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js');
// ?
browser.addDomElement('<script>...</script>');
````
