### ISSUE TITLE
GBK & Javascript Content

### ISSUE THREAD

**Issue by rainbowhat** [assaf/zombie#758]
Hi,

I've been trying to do the following
1) Load the fully loaded page content (You will realise from the link the item price does change after the browser/javascript is loaded)
If 1) it's possible , Extract part of HTML (Return Chinese Characters instead of å½“å‰ä½ç½®)

browser = Browser.create();
browser.visit("http://item.taobao.com/item.htm?spm=a230r.1.14.92.Bkiv1j&id=37307590641&ns=1#detail", function (error) {
console.log(browser.html());
res.json({ message: browser.source() });

Thanks in advance !

**Comment by ForbesLindesay** [comment]
I'm going to go ahead and close this, since it's a few years old.  Adding a simple timeout/delay may be the best approach for what you're trying to achieve.
