### ISSUE TITLE
Socket.IO 1.x cannot write to the socket

### ISSUE THREAD

**Issue by Langeh** [assaf/zombie#816]
I am a contributor to [NodeCG](http://github.com/nodecg/nodecg). NodeCG makes extensive use of Socket.IO, and utilizes Zombie for easy end-to-end testing of our socket functionality. Currently, NodeCG uses Socket.IO 0.9.17, and all of our tests work as expected ([test file](https://github.com/nodecg/nodecg/blob/master/test/api.js), [Travis results](https://travis-ci.org/nodecg/nodecg/jobs/42034780)).

However, we are in the process of migrating NodeCG to Socket.IO 1.x, specifically 1.2.1. In doing so, it seems that Socket.IO has ceased to function as expected in Zombie. Everything works as expected in an actual production environment with a real browser, but our Zombie-based tests do not.

I've created a [minimal test case](https://github.com/Langeh/socket.io-zombie-test) demonstrating Socket.IO's inability to write to the client-side socket. The server-side socket writing seems fine, it is only the client-side socket that fails.

**Comment by MattMcNam** [comment]
Hi @assaf,

We put this off for a while and looked into the issue again today. TL;DR, this issue can be closed :)

Because we are interacting with the socket.io objects outside of the browser page Zombie doesn't get a chance to process the event queue. Simply wrapping part of the test in `browser.wait` solves this.

**Comment by messutied-pf** [comment]
Sorry to write in an old ticket, but I'm having this exact issue, @MattMcNam could you elaborate on how you worked around this problem?

**Comment by MattMcNam** [comment]
@messutied-pf sorry, we switched away from zombie to selenium, webdriver and instances of Chrome quite a while ago as we needed more 'real' results

Using `browser.wait` may have worked for a while, but it's so long ago that I don't really remember the details. Best I can give you is this commit https://github.com/nodecg/nodecg/commit/4467991fdc008ce59a14d1cbebb6a81ea0b5c5ad
