### ISSUE TITLE
Problem when a web page makes an AJAX call

### ISSUE THREAD

**Issue by IGZJavierPerez** [assaf/zombie#835]
I want to test that when clicking a button, an AJAX request is made to a server.

Everything works correctly when the server returns 200 status code.

But when the server returns 405 code (or any other error status code), I can not verify that everything has happened as expected.

As far I could find out, Zombie is aborting the AJAX request, because in the client, I see that the AJAX request has a `readyState = 0` and the callback of the `pressButton` Zombie method is getting a message containing the statusCode returned by the server.

I do not know how to fix this but I think Zombie behavior is not correct. This behavior causes the client does not do what is expected

[Here](https://github.com/IGZJavierPerez/front-testing/blob/nock%2Bzombie%2Bcucumber/client/test/features/steps_definitions/from.register.definitions.js) you can see the tests y [here](https://github.com/IGZJavierPerez/front-testing/blob/nock%2Bzombie%2Bcucumber/client/register.html) the web page.

**Comment by scottbrady** [comment]
I think I'm experiencing the same bug.  I have a test where my server returns an HTTP 500 status for an XHR request so I can test that my frontend code handles the error.  This test was working for me with Zombie 2.0.8 but started failing after I upgraded to 2.5.1.  It seems like the new behavior is incorrect and doesn't match the behavior you would see in a "real" browser (Chrome, Firefox, etc).

**Comment by IGZJavierPerez** [comment]
I have checked that until 2.1.1 version XHR is working well. The problem is introduced since 2.3.0 version.

**Comment by onyxrev** [comment]
+1 2.1.0 works for me

**Comment by assaf** [comment]
This will be fixed in 3.0, a pre-release available via npm, but watch CHANGELOG for breaking changes
