### ISSUE TITLE
bluebird dep not installing in 2.5.1 or master

### ISSUE THREAD

**Issue by bevanhunt** [assaf/zombie#839]
I can't use Zombie as it doesn't include bluebird in the node_modules for this library when sudo npm installed. I copied and pasted the example code (modified to talk to my server) from the readme and I keep getting errors like:
[TypeError: Cannot call method 'add' of undefined]
[TypeError: Cannot call method 'add' of undefined]
[ReferenceError: Promise is not defined]

I am using node version 0.10.35 as zombie builds fail on 0.11.14

**Comment by assaf** [comment]
If npm is acting weird, delete and try to install again.
