### ISSUE TITLE
jsdom update

### ISSUE THREAD

**Issue by Likon84** [assaf/zombie#842]
Can someone update jsdom to version 2.0.0?
Zombie js have problem with html5 dom elements.

Regards

**Comment by medikoo** [comment]
_jsdom_ is now actually at v3, it'll be great to have zombie updated.

(if only it was not written in coffeescript ;)

**Comment by assaf** [comment]
Master is now using JSDOM 3.1.0 and you can get the pre-release from npm, but see CHANGELOG for breaking changes.
