### ISSUE TITLE
How to test redirects with custom protocols?

### ISSUE THREAD

**Issue by jaanus** [assaf/zombie#844]
I am writing some application tests with Zombie. Parts of my work include custom protocols: after submitting a POST, the server responds with a `302 Redirect` to something like `custom://example/url?custom=parameters`. Zombie, of course, does not know how to handle this, and will fail.

I saw that Zombie has support for hooking into processing requests and responses with Browser.Resources.addHandler, but I could not get it to work: no matter what I tried (e.g returning mock responses from the request handler), it kept failing with this bit in `window.coffee`:

    unless /^(about|javascript|http|https|file):/i.test(url)
        throw new Error("Cannot load resource #{url}, unsupported protocol")

What I would like to do: after I post a form, I would like to verify that the server issued the correct redirect, but not actually try to load that resource.

Is there a way to do this with the current APIs?

**Comment by assaf** [comment]
There's no support for custom protocol handlers. But you should have access to the server response, including the status code and URL.

**Comment by assaf** [comment]
This is addressed in 3.0, it will simply error and the document location will point to the non-HTTP URL.

A pre-release available via npm, but watch CHANGELOG for breaking changes
