### ISSUE TITLE
Is HTML node tree always up to date?

### ISSUE THREAD

**Issue by ChrisBAshton** [assaf/zombie#846]
Great library, but it doesn't seem to be executing all of my JS. I can set something basic, like:

```html
<script>
document.body.className += ' testTESTtestTEST';
</script>
```

And the JS is clearly executed because when I console.log the body of the page, the class is added. But I have a compiled, minified and complex codebase that I pull in as a single module using RequireJS, which replaces a link on the host page with a dynamic iFrame.

In browser, this works nicely and is backwards compatible to IE8. But it doesn't seem to work using Zombie - I set a setTimeout loop which, every second, does the following:

* finds the container div by class name
* console.logs the innerHTML
* I expect it to be a link to an iFrame for a second, but it should soon be replaced by an iFrame element. However, I can leave this loop running forever and the link is never replaced.

Is the HTML node tree always up to date, or is it cached after the page has loaded? Is there a way to clear the cache?

Thanks in advance

**Comment by assaf** [comment]
The HTML document tree is live, if you don't see a change, it never happened.
