### ISSUE TITLE
compile issue on v0.11

### ISSUE THREAD

**Issue by i5ting** [assaf/zombie#848]
✗ npm install zombie       
npm WARN package.json ncg@0.1.5 No repository field.
npm WARN package.json gutil@1.5.5 No repository field.
npm WARN engine zombie@2.5.1: wanted: {"node":"0.10.x"} (current: {"node":"0.11.15","npm":"2.1.6"})
npm WARN engine lazybird@1.0.0: wanted: {"node":"0.10.x"} (current: {"node":"0.11.15","npm":"2.1.6"})
 
/node_modules/zombie/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  SOLINK_MODULE(target) Release/bufferutil.node: Finished
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
  SOLINK_MODULE(target) Release/validation.node: Finished
\
\
 
> contextify@0.1.11 install 
/node_modules/zombie/node_modules/jsdom/node_modules/contextify
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
  CXX(target) Release/obj.target/contextify/src/contextify.o
../src/contextify.cc:31:17: error: no member named 'ContextDisposedNotification' in 'v8::V8'
        v8::V8::ContextDisposedNotification();
        ~~~~~~~~^
1 error generated.
make: *** [Release/obj.target/contextify/src/contextify.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 13.3.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd 
/node_modules/zombie/node_modules/jsdom/node_modules/contextify
gyp ERR! node -v v0.11.15
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
\

**Comment by assaf** [comment]
0.11 not supported, only 0.10 and soon 0.12.

**Comment by i5ting** [comment]
maybe its a common issue, keep watch 0.12.
