### ISSUE TITLE
Can multiple pages be tested async using tabs in Mocha?

### ISSUE THREAD

**Issue by SlightlyCyborg** [assaf/zombie#850]
I want to run tests on the relative url /users and on the relative url /users/add asynchronously. Can I do this using tabs. I can just imagine setting the browsers current tab to /users and then in the time it takes to run several assertions, the other test will change the current tab to /users/add and fail the remaining users/ asserts because the browser is no longer on the /users tab.

I would hate to have to run everything synchronously, but if tabs can't be used without changing the browsers state then I am not sure how this will work. Can I call browser.assert methods directly on tabs so I don't need to assert on the browsers current tab?

**Comment by assaf** [comment]
There's no multi-threading in JavaScript, when assertions are run the only thing running is assertions. You should be working on one tab at a time.

There's nothing magical about `browser.assert`, those are just convenience methods that use current window, you can write your own to use any tab.

**Comment by SlightlyCyborg** [comment]
Ok. So I would need to change to the correct tab in every async functions callback because the cpu is freed up to work on other tests until the call back is called and the current tab could/would change in those other tests. Am I correct in saying this?

**Comment by assaf** [comment]
Mocha doesn't run tests in parallel, and Zombie doesn't execute anything until you call `wait` (or equivalent function that will wait), and up until the callback.

**Comment by SlightlyCyborg** [comment]
Ok. Thnaks.
