### ISSUE TITLE
once again... events fire twice!?

### ISSUE THREAD

**Issue by HansHammel** [assaf/zombie#854]
I just discovered a lot of duplicate dom elements, when using zombie.js.

a simple function like 

	    var createlink = function (containerId, href, text, description, wrap) {
	        var e = document.getElementById(containerId);
	        if (!!e) {
	            var a = document.createElement('a');
	            a.innerHTML = text;
	            a.title = !!description ? description : '';
	            a.href = href;
	            e.appendChild(a);
	        }
	    };
	createlink('xxx', 'https://xxx, 'xxx', 'xxx');

seems to be executed twice!?

**Comment by assaf** [comment]
Maybe, but none of the tests in our test suite have this issue.
