### ISSUE TITLE
zombie.js not exiting

### ISSUE THREAD

**Issue by HansHammel** [assaf/zombie#855]
A simple test

	var Browser = require("zombie");
	var fs = require("fs");
	// Load the page from localhost
	browser = new Browser({
	   debug: true,
	    runScripts: true,loadCSS:true, userAgent: 'tester'
	    //,waitFor:5000, maxWait: 5000
	    });
	browser.visit("http://localhost/index.html",
	    function (err) {
	        if (err) throw err;
	        fs.writeFileSync('message.html', browser.html(),{encoding:'utf8'}, function (err) {
	            if (err) throw err;
	            console.log('It\'s saved!');
	        });
	
	});

is not exiting and not showing errors or any information in debug mode. wtf is happening here!?

**Comment by assaf** [comment]
`writeFileSync` doesn't accept callback as last argument, use `writeFile` instead.
