### ISSUE TITLE
Switch to plain JavaScript

### ISSUE THREAD

**Issue by medikoo** [assaf/zombie#857]
I'd like to contribute to the project, but use of CS is big obstacle in that.

Will you consider switch so this project is developed in plain JS?

**Comment by assaf** [comment]
https://github.com/assaf/zombie/tree/jsdom-3.1

**Comment by medikoo** [comment]
@assaf thanks, looks very promising, and I see it's nearly finished. I look forward!

**Comment by assaf** [comment]
Merged this branch into a master, and pre-release available via npm.
