### ISSUE TITLE
Provide a mechanism to continue processing after expected browser error...

### ISSUE THREAD

**Issue by the-t-in-rtf** [assaf/zombie#859]
I am using Zombie.js to test client-side modules that interact with an API served up by node.  The tests include "bad" inputs on the client side, which are sent to the server via a jQuery.ajax() call.   The API on the server responds with an appropriate error code and status, such as 401 ("not authorized").

Zombie's event loop immediately treats a status code above 400 as a "stop the world" event (see below the snippet from eventloop.js:259-261):

```
          if (response && response.statusCode >= 400) {
            error = new Error("Server returned status code " + response.statusCode + " from " + url);
          }
```

What should happen is that the client-side ajax error function should be given a chance to handle the error, and should see the API's message.

Instead, it appears that the original AJAX request is canceled, and the error function is called with a bogus error (whose status code is zero).

I propose adding a configuration option to disable this check.

**Comment by the-t-in-rtf** [comment]
I have created and submitted a pull request:
https://github.com/assaf/zombie/pull/860

**Comment by assaf** [comment]
Yes, it shouldn't error on XHR, all other cases should error.
