### ISSUE TITLE
document.querySelector() in browser.evaluate() script?

### ISSUE THREAD

**Issue by ahri** [assaf/zombie#862]
```javascript
var Zombie = require('zombie');

var browser = new Zombie();

browser.visit('http://google.co.uk', function () {
  console.log(browser.evaluate('document.readyState'));
  console.log(browser.evaluate('document.querySelector("head title").textContent'));
});
```

Results in:

    $ node foo.js
    complete
    ./node_modules/zombie/node_modules/bluebird/js/main/promise.js:626
                throw e;
                      ^
    Error: TypeError: Cannot read property 'textContent' of null
        at Object.ensureErrorObject (./node_modules/zombie/node_modules/bluebird/js/main/util.js:226:20)
        at Promise._rejectCallback (./node_modules/zombie/node_modules/bluebird/js/main/promise.js:416:22)
        at Promise._settlePromiseFromHandler (./node_modules/zombie/node_modules/bluebird/js/main/promise.js:460:17)
        at Promise._settlePromiseAt (./node_modules/zombie/node_modules/bluebird/js/main/promise.js:530:18)
        at Async._drainQueue (./node_modules/zombie/node_modules/bluebird/js/main/async.js:84:12)
        at Async._drainQueues (./node_modules/zombie/node_modules/bluebird/js/main/async.js:89:10)
        at Immediate.Async.drainQueues [as _onImmediate] (./node_modules/zombie/node_modules/bluebird/js/main/async.js:14:14)
        at processImmediate [as _immediateCallback] (timers.js:374:17)

So is the sizzle functionality not exposed to the runtime-evaluated JS? Is there a way to access this functionality from with a call to .evaluate() ?

**Comment by assaf** [comment]
1. Zombie no longer using Sizzle since many versions back.
2. You can access `browser.document` directly, `evaluate` is rarely necessary
3. As the error indicates, `querySelector` was called successfully, it simply didn't find the element in question

**Comment by ahri** [comment]
Ok I'm not actually bothered about Sizzle, just the functionality.

I appreciate that I can access it via browser.document, but wish to access it in evaluated code. I think this should work, e.g. I can use Chrome or Firefox, open up the console, and paste in:

    document.querySelector('head title').textContent

Which yields "Google".

So my question becomes: why is it null when it's not null in Chrome/Firefox? Can I work around this?

**Comment by assaf** [comment]
No idea what's on that web page and whether or not Zombie can parse it correctly.

**Comment by ahri** [comment]
Um... it's a little website called http://google.com - check it out sometime :)

```html
<!doctype html>
<html itemscope="" itemtype="http://schema.org/WebPage" lang="en">
   <head>
      <meta content="Search the world's information, including webpages, images, videos and more. Google has many special features to help you find exactly what you're looking for." name="description">
      <meta content="noodp" name="robots">
      <meta content="/images/google_favicon_128.png" itemprop="image">
      <meta content="origin" id="mref" name="referrer">
      <title>Google</title>
      <!-- there's a load of other stuff, but I snipped it -->
   </head>
</html>
```

It appears, at first glance, to be pretty straightforward to get the title tag, and it's a pretty popular website.

**Comment by assaf** [comment]
Maybe it should be made more clear in the README, but Zombie is intended for testing. I'm not interested in reviewing or discussing content on 3rd party sites.

**Comment by ahri** [comment]
Ok let's try this in bullet points, since you like those.

1. You want people to use Zombie for testing
2. Zombie should emulate actual browsers in order to be an effective testing tool
3. Zombie is not quite emulating real browsers in this regard; it seems to do fine for elements in the body but not the head
4. Chill out - I'm not demanding that you fix anything :) I'm asking if this is expected behaviour and whether I can work around it somehow (preferably in an evaluate() call)

Not doing something that real browsers do on the simple home page of the most popular search engine in the world (or at least in the western world) is probably not something that you should just brush off, but hey, it's your project, I'm just drawing your attention to a bug.

**Comment by assaf** [comment]
I don't care that Zombie can't scrape google.com or any other Google property.

**Comment by ahri** [comment]
Just because the bug is specifically present on Google doesn't really make it any less of a bug in your software, but I've obviously hit a nerve so I'll just leave it. Have a good day.
