### ISSUE TITLE
3.0.X-0: browser.resources.dump(), 'call' is undefined within core-js.js getIterator

### ISSUE THREAD

**Issue by mmehlhope** [assaf/zombie#863]
Using 3.0.3-0 through 3.0.6-0 our team has been seeing the following:

    TypeError: Cannot call method 'call' of undefined
    at Function.getIterator (/test/node_modules/zombie/node_modules/6to5-runtime/core-js.js:496:31)
    at Resources.dump (/test/node_modules/zombie/lib/resources.js:161:123)
    ...

Current stable versions do not have this issue, but we've upgraded to the 3.x.x releases for the improved XHR support.

**Comment by scottbrady** [comment]
I've seen the same issue with the 3.0 branch.

**Comment by assaf** [comment]
Just pushed 3.0.7 to npm, give it a try

**Comment by mmehlhope** [comment]
Hi Assaf,

Thanks for the quick update, it is much appreciated. Unfortunately, it seems the bug still remains (but is now caused from a slightly different place within the Resources.dump() iterator function:

    Warning: Command failed: ^--- With additional stack trace: TypeError: Cannot call method 'call' of undefined
      at Function.getIterator (/test/node_modules/zombie/node_modules/babel-runtime/core-js.js:550:31)
      at Resources.dump (/test/node_modules/zombie/lib/resources.js:167:123)

**Comment by assaf** [comment]
![](http://blog.codinghorror.com/content/images/uploads/2007/03/6a0120a85dcdae970b0128776ff992970c-pi.png)

But seriously, I tried calling it on a new browser object and a browser with open documents, on Node 0.10 and 0.12, not seeing any errors.
