### ISSUE TITLE
"REMOVED Browser.dns and Browser.ports, switching to different implementation"

### ISSUE THREAD

**Issue by wernight** [assaf/zombie#868]
CHANGELOG of version 3 says `REMOVED Browser.dns and Browser.ports, switching to different implementation` without saying how to migrate code using those methods. I saw a `reroute` which doesn't seem to be accessible.

Use case: Using Docker, my actual website is under a hostname `web:8080` so I'd want all `www.something.com` to go to `web:8080` instead (which `Browser.dns` allowed).

**Comment by wernight** [comment]
Seems that `reroute` should be exposed in `src/index.js`

**Comment by assaf** [comment]
I'm trying to reduce some of the things Zombie does, so this will likely become it's own npm. Meanwhile you can access it via `require('zombie/lib/reroute')`

**Comment by wernight** [comment]
Even though my changes would solve this problem, the name `localhost` would be wrong. Parameter order is also a bit odd (looks like SSH order).

**Comment by wernight** [comment]
This second solution is more what I think would make the API cleaner, leaner, and more generic.

**Comment by assaf** [comment]
`Browser.localhost` is just that, a simple solution to the very common use case, where you're running a local test server on unprivileged port, and you want it to appear like production server.

For anything more complicated, first see your operating system's IP routing table, and if that doesn't work, you can consider using a hack like reroute as a standalone module.

**Comment by wernight** [comment]
Why not expose site (already exposed actually) and reroute like the proposed pull? It's a clean solution that is simpler and avoids having magic logic and solves two common cases:
- server on another domain/IP during tests
- multiple servers

PS: What is not covered here but for me helped me a lot more than having `localhost()` was understanding that I could put a global `before()` (outside any `describe()`) and *Mocha* would execute it once before any other test script in that directory. This is a good place to do `Browser.site`and `Browser.reroute()`.

I tried using `require('zombie/src/reroute')` but it seems that the script fails on `let default = false;` even though I loaded *Babel* and my scripts are using ECMAScript 6. Not saying it cannot work, just why make it more difficult? I think having the `localhost` help instead of `reroute` is trying to solve a case that isn't so common, harder to understand, and fails to help as much as `reroute` does.

**Comment by assaf** [comment]
`Browser.site` is officially supported, it allows you to call `browser.visit` with relative paths. It can be used in combination and separately from `browser.localhost`.

Zombie is not in a tool for addressing DNS resolution / IP routing, hence it's not going to expose an API for that. Zombie was designed so you can, within the same Node process, run both browser and server code, hence dealing with localhost is a core feature.

Babel doesn't transpile code in the `node_modules` directory, that's why you need to `require('zombie/lib/reroute')` notice it's "lib" and not "src". At any rate, this will only work with latest release and probably break in the future, so not too concerned about making it easy.

**Comment by wernight** [comment]
You seem to have a clear vision. That's fine. May be you could update README with a pointer to that dns package if you plan to release it.

Keep in mind Zombie is also good for any website testing and end to end testing. That means for me that it's done better when the testing environment (zombie) is really outside the tested website.
