### ISSUE TITLE
Setting http.Agent keepAlive

### ISSUE THREAD

**Issue by sjparkinson** [assaf/zombie#872]
Hi, I'm currently using zombie.js in combination with [Behat/MinkZombieDriver][1] and am having trouble with nodes default http settings.

I'd like to enable the [http.Agent keepAlive](http://nodejs.org/api/http.html#http_new_agent_options) option to reuse sockets between requests to the same host, to more closely mimic browser behaviour.

In [Behat/MinkZombieDriver/src/Behat/Mink/Driver/NodeJS/Server/ZombieServer.php][2] I have something like:
```js
var net      = require('net'),
    zombie   = require('zombie'),
    browser  = null,
    pointers = [],
    buffer   = '',
    host     = '%host%',
    port     = % port % ;

net.createServer(function (stream) {
    stream.setEncoding('utf8');
    stream.allowHalfOpen = true;

    stream.on('data', function (data) {
        buffer += data;
    });

    stream.on('end', function () {
        if (browser == null) {
            browser = new zombie();

            // Clean up old pointers
            pointers = [];
        }

        try {
            eval(buffer);
            buffer = '';
        } catch (e) {
            buffer = '';
            stream.end('{$errorPrefix}' + JSON.stringify(e.message));
        }
    });
}).listen(port, host, function () {
    console.log('server started on ' + host + ':' + port);
});
```

I've tried requiring `http` and then adding `http.globalAgent.maxSockets = 1;` and also `http.globalAgent.options.keepAlive = 1;`, but I'm still seeing node/zombie create new connections on different requests to the same host.

Ideally I'm just looking for a pointer in the right direction. If it makes a difference I'm making the requests over SSL.

[1]: https://github.com/Behat/MinkZombieDriver
[2]: https://github.com/Behat/MinkZombieDriver/blob/v1.2.0/src/Behat/Mink/Driver/NodeJS/Server/ZombieServer.php#L62-L192

**Comment by assaf** [comment]
If you're using HTTPS then you need to set `https.globalAgent`.

**Comment by sjparkinson** [comment]
No luck unfortunately, I've tried a few things but nothing that worked. This was what I ended up with:

```js
https.globalAgent.options.keepAlive = true;

net.createServer(function (stream) {
    stream.setEncoding('utf8');
    stream.allowHalfOpen = true;

    stream.on('data', function (data) {
        buffer += data;
    });
```
