### ISSUE TITLE
Wrong relative CSS paths when using @import

### ISSUE THREAD

**Issue by IonicaBizau** [assaf/zombie#873]
I have a CSS file located at `/theme/css/style.css`:

```css
/* fonts and tomorrow theme */
@import url(http://fonts.googleapis.com/css?family=Gentium+Book+Basic:400,700&subset=latin,latin-ext);
@import url(http://fonts.googleapis.com/css?family=Open+Sans:400,800&subset=latin,latin-ext);
@import url("./tomorrow.css");

@import url("http://cdnjs.cloudflare.com/ajax/libs/animate.css/3.1.0/animate.min.css");
@import url("http://netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.css");

/* markdown css */
@import url("./markdown.css");

/* ... */
```

However the relative paths `./tomorrow.css` and `./markdown.css` are returned as absolute paths (e.g. `http://localhost:9000/tomorrow.css`).

My code is:

```js
// Dependencies
var Browser = require("zombie");

// Load localhost:9000
Browser.localhost("localhost:9000");

// Load the page from localhost,
// including js, css, images and iframes
var browser = new Browser({
  features: "scripts css img iframe"
});

// Open the page and list the resources
browser.visit("/", function(error) {
    console.log(browser.resources.map(function (c) {
        return c.request.url;
    }));
});
```

Is this a bug or I'm doing something wrong?

**Comment by assaf** [comment]
Probably a bug

**Comment by IonicaBizau** [comment]
@assaf If you told me where I should start debugging, I would be happy to contribute.

**Comment by assaf** [comment]
Stylesheet parsing handled by CSSOM, which gets the page URL from JSDOM. When loading images and scripts, JSDOM uses `loader.resolver` to resolve relative URLs, so maybe it's doing the same thing with CSS.

**Comment by IonicaBizau** [comment]
@assaf If you could debug and fix it I would be so thankful...!

**Comment by assaf** [comment]
I'm not going to have any time to work on this, sorry

**Comment by dbo** [comment]
FYI, I think this is a bug in jsdom, I have a [fix/pull request](https://github.com/tmpvar/jsdom/pull/1105).

**Comment by dbo** [comment]
FYI, second pull request with test accepted, jsdom 5.2.0 has the fix.

**Comment by IonicaBizau** [comment]
@dbo Awesome! Thanks a lot! :+1:

**Comment by assaf** [comment]
@dbo thanks for the fix!

Just releases Zombie 4.0.10 which uses JSDOM 5.2.0
