### ISSUE TITLE
use node-pre-gyp?

### ISSUE THREAD

**Issue by Pomax** [assaf/zombie#874]
Needing python and visual studio for windows so that node-gyp actually works is typically of a full day's worth of hate-fest, whereas getting the precompiled binary because a project uses [node-pre-gyp](https://www.npmjs.com/package/node-pre-gyp) is the most amazingly painless way to just get the library during `npm install` on "you shouldn't even need to care which OS you're on", so you can just get on with the job of writing and testing code.

**Comment by assaf** [comment]
If you have time to help, this is the right thread: https://github.com/brianmcd/contextify/issues/63

**Comment by Pomax** [comment]
left a comment, thanks for the redirect.
