### ISSUE TITLE
NPM release of version 3.x

### ISSUE THREAD

**Issue by wernight** [assaf/zombie#879]
What about a beta release of 3.x or even a normal release as most people won't auto-upgrade to major releases automatically. NPM is still only referencing version 2.x.

**Comment by wernight** [comment]
As a workaround I found that `git+https://github.com/assaf/zombie.git#3ebc0e99314f00b420427ac717f90bcc543f96fb` installs what it marked (but not tagger) as version 3.0.12.

**Comment by assaf** [comment]
All 3.0.x releases are available via NPM. To install:

```
npm install zombie@next
npm install zombie@3.0.14-0
```

Without tag/version, npm installs `@latest` that still points to 2.5.1 and will until some further testing.

**Comment by wernight** [comment]
Ah thanks.
