### ISSUE TITLE
Cannot run zombie.js using browserify

### ISSUE THREAD

**Issue by justgeek** [assaf/zombie#892]
Running browserify command to output a bundle file : 
browserify main.js -o bundle.js

main.js : 
var browser = require("zombie");
b = new browser();
b.visit("http://www.google.com/", function (err, browser) {
  if (err) { console.log('Error:' + err.message); }
  else {
   console.log(b.window.document.title) 
}
  // ... rest of your code here
});

always get the following error : 

Error: Cannot find module 'coffee-script' from 'c:\browserify'
    at C:\Users\Mohammed Taher\AppData\Roaming\npm\node_modules\browserify\node_
modules\resolve\lib\async.js:46:17
    at process (C:\Users\Mohammed Taher\AppData\Roaming\npm\node_modules\browser
ify\node_modules\resolve\lib\async.js:173:43)
    at ondir (C:\Users\Mohammed Taher\AppData\Roaming\npm\node_modules\browserif
y\node_modules\resolve\lib\async.js:188:17)
    at load (C:\Users\Mohammed Taher\AppData\Roaming\npm\node_modules\browserify
\node_modules\resolve\lib\async.js:69:43)
    at onex (C:\Users\Mohammed Taher\AppData\Roaming\npm\node_modules\browserify
\node_modules\resolve\lib\async.js:92:31)
    at C:\Users\Mohammed Taher\AppData\Roaming\npm\node_modules\browserify\node_
modules\resolve\lib\async.js:22:47
    at FSReqWrap.oncomplete (fs.js:95:15)

testing standalone zombie with node works as expected , but failed to run with browserify , any idea what may be wrong ?

**Comment by assaf** [comment]
Zombie is designed for io.js/Node.
