### ISSUE TITLE
NPM release versions 4.X

### ISSUE THREAD

**Issue by cookch10** [assaf/zombie#893]
Could you please publish the the 4.X releases of zombie to npm?

**Comment by assaf** [comment]
It's on npm, you can use `npm info` to find all published versions and install it, or install with the tag `next`.

**Comment by cookch10** [comment]
Ah yes, I see it with `npm view zombie versions`.  I was going by the "3.1.1 is the latest of 116 releases" copy seen on https://www.npmjs.com/package/zombie.
