### ISSUE TITLE
Where has the documentation gone ?

### ISSUE THREAD

**Issue by ceymard** [assaf/zombie#897]
The labnotes site now forwards to non exitent github pages.

Where can we consult the documentation ? Without the API, it is pretty hard to get anything done.

Thanks for this great util anyway :)

**Comment by ciscoheat** [comment]
I just created zombiejs externs for Haxe, so until the page is up you can find a compressed API here: https://github.com/ciscoheat/haxe-js-kit/blob/dev/js/npm/zombie/Browser.hx

**Comment by assaf** [comment]
If you're referring to the `/API` page, that belongs to the Zombie 2.x documentation set. I updated the site with the docs for 4.x which are all in one page.

The source documentation is always available in the `npm` package, so if you can't access it online, you can check there.

**Comment by taavo** [comment]
Looks like some useful methods were left out of the 4.x documentation. For example, nearly everything in index.js: accessors, forms, navigation, etc. These are pretty essential to using zombie, and we would have loved to have found them in the docs when we were getting started with it (earlier this week).

/cc @mkenyon

**Comment by assaf** [comment]
I could definitely use help with finishing up the new documentation.

**Comment by mkenyon** [comment]
What did you use to help write the [current Github page](http://zombie.js.org/)? Did you extract anything out of the source code or did you write it manually?

The docs you've already written provide excellent examples, so maybe all we need now is an API page. The code has great comments, so it'd be awesome if we could generate documentation directly from there.

**Comment by assaf** [comment]
Usually, I start by copying the comment from the source code and build from that. Some methods are trivial, just copy & paste from the source code. But where necessary, the docs add more color, code samples, lengthy explanations. Can't do that with automated tools.

I prefer to keep the entire documentation in a single page. It's easier to edit/generate and also easier to navigate: there's a ToC at the top for quickly jumping between topics, and it's easier to search in page.
