### ISSUE TITLE
"May" is not a Strong Word for Software

### ISSUE THREAD

**Issue by benderTheCrime** [assaf/zombie#899]
Can you please add more specificity around what is implied by *"may work with Node 0.12"*? I'm running Node 0.12.1 and the latest version of Zombie after upgrading to avoid an issue described here:

https://github.com/assaf/zombie/issues/181

Which is (despite the status) unresolved for legacy 3.4.x versions. I am now running into an uncaught TypeError after having changed no code associated with my tests.

* *What confidence should I have in the fact that 4.x.x may work with Node 0.12?*
* *Are there tests around the performance of this library in Node 0.12?*
* *Is there going to be any development supporting future Node versions?*

I've enjoyed using your library thus far and would like to continue doing so in Node.

**Comment by assaf** [comment]
The short answer is: Zombie 4.x is written and tested to work correctly on io.js.

The test suite passes under Node 0.12 (see https://travis-ci.org/assaf/zombie/builds/58037512), however, those tests are fairly simple, it may well refuse to work correctly on more complex test scenarios.

There are no performance tests.

I don't know what Node will do in the future, right now they're shipping a version that's far behind on the evolutionary path. There's some talk about them catching up and merging with io.js.

**Comment by assaf** [comment]
Updated README.
