### ISSUE TITLE
npm WARN engine zombie@4.0.8: wanted: {"node":"^1.6.0"} (current: {"node":"0.12.2","npm":"2.7.5"})

### ISSUE THREAD

**Issue by zwb-ict** [assaf/zombie#901]
The newest node isn't 0.12.2 ???

**Comment by assaf** [comment]
Yes, see changelog: https://github.com/assaf/zombie/blob/master/CHANGELOG.md

**Comment by zwb-ict** [comment]
I am very very sorry, I didn’t see README and Changelog carefully, then bothered you! After reading them, I have solved my problem. Happy Weekend！ 

-- 
zwb.ict
Sent with Airmail

在 2015年4月23日 上午12:14:25, Assaf Arkin (notifications@github.com) 写到:

Yes, see changelog: https://github.com/assaf/zombie/blob/master/CHANGELOG.md
