### ISSUE TITLE
Error: timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.

### ISSUE THREAD

**Issue by zwb-ict** [assaf/zombie#902]
var Browser = require('zombie'),
	assert = require('chai').assert;

var browser;

suite('Cross-Page Tests', function(){

	setup(function(){
		browser = new Browser();
	});

	test('requesting a group rate quote from the hood river tour page should ' +
			'populate the hidden referrer field correctly', function(done){
		var referrer = 'http://localhost:3000/tours/hood-river';
		browser.visit(referrer, function(){
			browser.clickLink('.requestGroupRate', function(){
				assert(browser.field('referrer').value === referrer);
				done();
			});
		});
	});

	test('requesting a group rate from the oregon coast tour page should ' +
			'populate the hidden referrer field correctly', function(done){
		var referrer = 'http://localhost:3000/tours/oregon-coast';
		browser.visit(referrer, function(){
			browser.clickLink('.requestGroupRate', function(){
				assert(browser.field('referrer').value === referrer);
				done();
			});
		});
	});

	test('visiting the "request group rate" page dirctly should result ' +
			'in an empty value for the referrer field', function(done){
		browser.visit('http://localhost:3000/tours/request-group-rate', function(){
			assert(browser.field('referrer').value === '');
			done();
		});
	});

});

I install the lastest zombie, then run mocha -u tdd -R spec -t 10000 qa/tests-crosspage.js, got Error: timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.

I changed the version to     "zombie": "~2.0.0-alpha31", then the test is OK.

**Comment by Iancurtis** [comment]
I got the same error , @zwb-ict
