### ISSUE TITLE
Can we do the assertion in the callback of `browser.visit` as the document shows?

### ISSUE THREAD

**Issue by freewind** [assaf/zombie#903]
In the document of http://zombie.js.org/, there is an example:

```js
browser.visit('/path', function() {
  assert(browser.location.href == 'http://example.com/path');
});
```

It does the assertion in the callback of `browser.visit`, is it the correct way?

When I use `mocha` to run such a test, I found it always success, even if the assertion is failed.

I searched the keyword `browser.visit` in the codebase of zombie, didn't find similar usage, instead, it does the assertion out of the `visit`, like:

```js
before(function(done) {
    browser.visit('/path', function() { done(); });
});

it("should do something", function() {
   assert(browser.location.href == 'http://example.com/path');
});
```

I'm not sure which is the correct way.

**Comment by assaf** [comment]
Check the example at the very top of the documentation. Semantically, this is the better way to write tests: the test body makes assertion about the document, loading that document happens in the setup (`before` in Mocha).

The second example you cited is just to illustrate how `Browser.localhost` works. However, in practice it should work just like the first example. If it doesn't, I would appreciate a pull request with a test case to show where it fails.

**Comment by freewind** [comment]
I made a test case for it. Basically followed the that test, with some small differences:

https://github.com/freewind/zombiejs-test/blob/master/test/assert-in-visit-callback-spec.js#L14

```js
describe('assert in visit callback', function() {
        it('should fail the test if the assertion failed"', function() {
            browser.visit('/hi', function() {
                console.log("############ location: " + browser.location.href);
                assert(browser.location.href == 'http://example.com/hi-wrong-path');
            });
        });
    });
```

Run test:

```
npm install
npm install -g mocha
mocha test/assert-in-visit-callback-spec.js
```

The test is passed, and found the code in the callback of `browser.visit` is not executed (maybe that's why the test can be passed)

Not sure the best way to fix it, thanks for replying

**Comment by assaf** [comment]
If the behavior is incorrect, the test should fail, we know the issue is fixed when the test finally passes.

**Comment by freewind** [comment]
@assaf thanks for the quick reply. Not quite get you, so I updated my previous reply to make it clear

**Comment by assaf** [comment]
You don't see anything in the log because there's no `done` callback.

**Comment by freewind** [comment]
Thanks, yes, that may be the reason. But I just followed the sample code:

```js
browser.visit('/path', function() {
  assert(browser.location.href == 'http://example.com/path');
});
```

There is no `done`. Is the sample code correct, or do I miss anything?

And I added `done` like this:

```js
describe('assert in visit callback', function() {
	const browser = new Browser();
	it('should fail the test with "done" if the assertion failed', function(done) {
		browser.visit('/hi', function() {
			console.log("############ location: " + browser.location.href);
			assert(browser.location.href == 'http://example.com/hi-wrong-path');
			done();
		});
	});
});
```

This time it will fail, but the reason is `timeout`:

```
  User visits /hi
    assert in visit callback
############ location: http://example.com/hi
      1) should fail the test with "done" if the assertion failed


  0 passing (2s)
  1 failing

  1) User visits /hi assert in visit callback should fail the test with "done" if the assertion failed:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
```

It's not about the assertion result, but `timeout`, which is not what I expected. What's the correct code that will show the real failure?

PS: I'm pretty new to zombiejs, although have spent several days on it, still not very clear about what is the accuracy behaviour of some of the methods. I may lack some background information, really appreciate if you can show me some live code :)

**Comment by assaf** [comment]
That sample code is not a Mocha test case, it illustrates how to set `Browser.localhost`. If you want a sample Mocha test case, look at the top of the README.

**Comment by freewind** [comment]
Ok, got it finally, it's just some kind of pseudocode? It will be great help if we put the tip around it

As my understanding, the correct way is:

```js
describe('assert in visit callback', function() {
    	const browser = new Browser();
    	before(function(done) {
		browser.visit('/hi', function() {
			done();
		});
    	});

	it('should fail the test with "done" if the assertion failed', function() {
		assert(browser.location.href == 'http://example.com/hi-wrong-path');
	});
});
```

This time it give correct output as I expected:

```
➜  zombiejs-test git:(master) ✗ mocha test/assert-in-visit-callback-spec.js


  User visits /hi
    assert in visit callback
      1) should fail the test with "done" if the assertion failed


  0 passing (50ms)
  1 failing

  1) User visits /hi assert in visit callback should fail the test with "done" if the assertion failed:

      AssertionError: false == true
      + expected - actual

      +true
      -false

      at Context.<anonymous> (test/assert-in-visit-callback-spec.js:41:4)
```

The main points are:

1. we should put the `browser.visit` in `before`
2. we should NOT assert in the callback of `visit`
3. we should assert in a separate `it`

Is it right?

**Comment by assaf** [comment]
Almost, your code doesn't pass any errors from Zombie to Mocha's `done` method.

**Comment by freewind** [comment]
Thanks, much clear now. One thing is not very sure is:

```
browser.visit('/hi', function() {
    // Shall we never do any assertion here in the callback of `browser.visit` ?
});
```

In my current understand, we should never do it. Right?

(Just feel can't catch your accurate meaning sometimes because of my English problem, so I ask it again. Thanks for the patience)

**Comment by assaf** [comment]
That is right. Use `before` blocks for navigation (`browser.visit`, `clickLink`, etc), `it` blocks for assertions.

**Comment by freewind** [comment]
Thanks, get it now. Appreciate your help!

**Comment by jrpool** [comment]
“Use before blocks for navigation (browser.visit, clickLink, etc), it blocks for assertions.”

Is this even possible when we want to assert that a page or element does not exist? Does the before callback not throw an error then and stop the test from being reached?
