### ISSUE TITLE
Make v4 compatbile with nodeJS

### ISSUE THREAD

**Issue by jlchereau** [assaf/zombie#911]
+1

**Comment by assaf** [comment]
Don't hold your breath. Zombie (by means of JSDOM) depends on the new VM implementation that was contributed last year and merged into io.js, but somehow ignored by Node.js maintainers. And it doesn't look like Node.js is maintained anymore except for critical patches.

**Comment by grrowl** [comment]
This is a confusing deal-breaker for me, as [iojs is about to be merged into nodejs](https://github.com/nodejs/io.js/issues/1664) any day now. So, we'll see what happens.

**Comment by interactionist** [comment]
+1

**Comment by mschultheiss83** [comment]
+1

**Comment by reyy** [comment]
+1
I'm still stuck on v2

**Comment by akreienbring** [comment]
+1
3.1.1 seems to work but crashes sometimes because of some JSDOM error :-(

**Comment by tejans24** [comment]
+1 
Please make this happen

**Comment by danhalliday** [comment]
+1

**Comment by OP-Klaus** [comment]
+1

**Comment by akreienbring** [comment]
Has anybody tested the current version of Zombi with the new node.js 4.0? As node.js 4.0 is mostly based on io.js this should probably work...

**Comment by MethodGrab** [comment]
Zombie 4.1.0 is working fine for me in Node 4.1.0.
