### ISSUE TITLE
Multipart submission breaks for simple values on Zombie 4

### ISSUE THREAD

**Issue by stof** [assaf/zombie#928]
the value will be received wrong in the backend:

```
Content-Length: 3

Bar
```

this issue has been detected in https://github.com/minkphp/MinkZombieDriver/issues/132#issuecomment-115263246 when running our testsuite using Zombie 4 rather than Zombie 3 to see the work to be compatible.

I think the bug is on https://github.com/assaf/zombie/blob/31d20706c32e2951a5dc6534a085113d3d1a023e/src/fetch.js#L166 which adds 2 CRLF while it is not the final header, meaning than the next line with the ``Content-Length`` will not be parsed as a header anymore

**Comment by assaf** [comment]
Thanks, fixed in 4.0.13

**Comment by stof** [comment]
Closing as @aik099 confirmed that it fixed the failure in our testsuite when running against Zombie 4.0.13. Thanks for the quick fix

**Comment by stof** [comment]
@assaf is it expected that the repo does not contain tags for the few latest releases ?

**Comment by assaf** [comment]
All releases have a commit associated with them (e.g. https://github.com/assaf/zombie/commit/0382cf3442a62db4dea0cca563335137e3ad7083). Some are tagged some are not, it's a flakey publish script.
