### ISSUE TITLE
API documentation removed after v2?

### ISSUE THREAD

**Issue by RyanBreaker** [assaf/zombie#934]
Zombie 2.5.1 had a pretty good and comprehensive API documentation (https://github.com/assaf/zombie/tree/v2.5.1/doc), but in v3 it was since removed and not readded. Why was it removed?

**Comment by assaf** [comment]
3.x has different API from 2.x. The major version bump indicates they're not backward compatible.

**Comment by RyanBreaker** [comment]
Any chance that new API documentation can or will be produced for v3 and/or v4? It's kind of a pain to have to look in the source to find everything.

**Comment by CacheControl** [comment]
:+1: Did the major version bump really invalidate *all* those docs?  Sucks to lose solid documentation, especially given that basic operations are currently missing (e.g. no mention of ```browser.click```).

**Comment by assaf** [comment]
No, but there's a few (non backwards compatible) API changes, that it warranted a major version bump and the old docs are "use at your own risk".

**Comment by ForbesLindesay** [comment]
Duplicate of #799
