### ISSUE TITLE
Zombie is looking for tough-cookie

### ISSUE THREAD

**Issue by geraldvillorente** [assaf/zombie#955]
`Error: Cannot find module 'node_modules/zombie/node_modules/tough-cookie'`

**Comment by assaf** [comment]
It's a required dependency and should be installed by npm.

**Comment by attila** [comment]
I found the problem was with npm@3 where tough-cookie is installed under `node_modules`. Reverting back to node 4.x which ships with npm 2.x made it work again.

**Comment by chris-fa** [comment]
How is this solved?

**Comment by davidmpaz** [comment]
I'm having same issue. My env is:

npm: 3.8.6
node: v6.0.0
zombie: 4.2.1

I have tough-cookie installed in `node_modules` but zombie error says it is looking for it inside `zombie/node_modules/tough-cookie`.

**Comment by chris-fa** [comment]
@davidmpaz did you have to install zombie as a global npm package?

**Comment by m1n0** [comment]
I am having the same issue, zombie installed as local npm package, my env is:
npm: 3.10.9
node: v7.2.0
zombie: tried both latest stable and master from git

**Comment by rask** [comment]
Same issue here, cannot run Zombie in our CI environment because of this error.

**Comment by rbrisita** [comment]
Anyone working on a legacy project will be interested in installing an older version of Zombie.js with:
```
npm install --save-dev npm-2
node_modules/.bin/npm-2 install --save-dev zombie@4
```
