### ISSUE TITLE
Documentation is missing a list of actions you can execute on the browser

### ISSUE THREAD

**Issue by ingro** [assaf/zombie#958]
Hello, I want to use this library to write some functional tests for a heave client-side project. Looking at the docs I didn't found anywhere how to, for example, click a link on the page, I had to dig the issues to find the right function.

I'm missing something or they are missing indeed?

**Comment by freewil** [comment]
:+1: needs documentation

**Comment by askogvold** [comment]
:+1:

**Comment by NeCkEr** [comment]
+1

**Comment by cicloon** [comment]
+1

**Comment by Bramanga** [comment]
👍

**Comment by ForbesLindesay** [comment]
Duplicate of #799
