### ISSUE TITLE
When calling dump() data is cut short

### ISSUE THREAD

**Issue by danielb2** [assaf/zombie#962]
Calling `browser.dump()`  but the document section is cut short by ellipsis.  How can I get the full `Document` ?

**Comment by assaf** [comment]
`browser.document`

**Comment by danielb2** [comment]
how about getting the raw html? is there something to call on the html object? I tried toString()

**Comment by assaf** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Element/outerHTML

**Comment by danielb2** [comment]
neither `browser.document.outerHTML` nor `browser.outerHTML` worked.  What am I missing?

**Comment by danielb2** [comment]
`browser.html()` worked ... 😓
