### ISSUE TITLE
API Reference

### ISSUE THREAD

**Issue by z-vr** [assaf/zombie#977]
Hi where can I find a documentation for all available methods such as 
browser.clickButton, browser.clickLink, browser.evaluate, etc? Those are the ones I saw on the Internet, but they are not described anywhere on the project's website. Many thanks.

**Comment by assaf** [comment]
http://zombie.js.org and for the rest you'll have to read through the source code.

**Comment by z-vr** [comment]
That's what I meant, there is no reference to clickButton on zombie.js.org. Will read through the source code then.

**Comment by ohenepee** [comment]
devres.zoomquiet.io/data/20110811173813/index.html

BTW, assaf... its pretty embarrassing to direct/expect newbies to be reading source code...

**Comment by assaf** [comment]
You're more than welcome to help and contribute some documentation

**Comment by alexserver** [comment]
@z-vr here is the reference for pressButton https://github.com/assaf/zombie/blob/master/src/index.js#L929

@assaf , at least this one should be in the README, since it's in the examples...
You'll need some extra help as I've seen many unattended pull requests.

Great tool, though.

**Comment by ForbesLindesay** [comment]
Duplicate of #799
