### ISSUE TITLE
How to stream/pipe from response object

### ISSUE THREAD

**Issue by ohenepee** [assaf/zombie#980]
How can I download a file with Zombie.js with a web app that uses http-equiv meta tag to emulate the Refresh HTTP header? (My test app actually downloads the file I want but I can't get it... I can tell it's being downloaded by watching my network graph anytime I invoke the download)

In essence how do you download/stream/pipe a downloadable resource that is loaded after sometime have passed and not via a direct download link.

I was thinking I could do it with the Zombie.js Pipeline... but the docs on that are not explanatory enough.

**Comment by z-vr** [comment]
I was trying to do it with the pipeline using response's _stream property, however because I read the stream manually, I would get an error when Zombie tried to read it later. So the solution is that you can wait for the page to load, and then find needed resources in browser.resources, and dump the `resource.response.body` property.

**Comment by ohenepee** [comment]
SOLVED IT (META REFRESH based file downloads)
```
var 
fs = require('fs'), 
URL = require('url'), 
Request = require('request'), // Named 'Request' to prevent conflict with zombie's 'request' object
Browser = require('zombie'), 
browser = new Browser(), 

browser.on('request', function (request) {
	
	// let's pullover for a download incase we find our request signboard :)
	if (request.url.indexOf('https://matchingString') == 0) {
		
		console.log('Beginning download in a flash...');
		
		var 
		parsedURL = URL.parse(request.url), 
		cookies = browser.cookies, 
		cookieHeader = cookies.serialize(parsedURL.hostname, parsedURL.pathname);
		
		if (cookieHeader) request.headers.append('Cookie', cookieHeader);
		
		var writeStream = fs.createWriteStream(pathToFileYetToBeWritten);
		
		writeStream
		.on('error', function(err) {
			console.error(err);
		})
		.on('finish', function() {
			console.log('finished writing file');
		});
		
		Request({
			method: request.method, 
			uri: request.url, 
			headers: request.headers.toObject(), 
			proxy: browser.proxy, 
			body: request.body, 
			jar: false, 
			followRedirect: false, 
			strictSSL: browser.strictSSL, 
			localAddress: browser.localAddress || 0
		})
		.on('error', function(err) {
			console.error(err);
		})
		.pipe(writeStream);
		
	}
	
});


	
browser.visit(url, function () {

	browser.wait(6000); // Wait only if you need to
	
});
```

@z-vr Your solution doesn't help if binary files (even of a moderate size) are involved...
